// Code generated by "stringer -type Server"; DO NOT EDIT.

package api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LlamaCPP-0]
	_ = x[VLLM-1]
	_ = x[OpenRouter-2]
	_ = x[Cerebras-3]
}

const _Server_name = "LlamaCPPVLLMOpenRouterCerebras"

var _Server_index = [...]uint8{0, 8, 12, 22, 30}

func (i Server) String() string {
	if i < 0 || i >= Server(len(_Server_index)-1) {
		return "Server(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Server_name[_Server_index[i]:_Server_index[i+1]]
}
